POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "trya",
    "password": "tryagain",
    "email": "afganistan1@gmail.com"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "kath",
    "password": "kath@"
}

###
GET  http://localhost:5000/myProfile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdGhjaXIxNTEyIiwiaWF0IjoxNzU2NzI2OTI3LCJleHAiOjE3NTY3MjY5NDJ9.w8D9i5LQ4DRmv2vqN0E8ANu6IyvIEvTs56Z-yoBGx18

###
POST http://localhost:5000/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdGhjaXIxNTEyIiwiaWF0IjoxNzU2NzI2ODc4LCJleHAiOjE3NTczMzE2Nzh9.0XAVapfx0Enboob_9OxRXyv33i15YgTsUMJ0Aj4jln0
Content-Type: application/json

{
    "username": "kathcir1512"
}

###
GET  http://localhost:5000/api/auth/allUsers
